config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'prototypes#index'
  resources :prototypes, only: [:index, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prototype.rb
class Prototype < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :profile, :occupation, :position, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  def index
    @prototypes = Prototype.all
  end

  def new
    @prototype = Prototype.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
            <div class="nav__right">
            <% if user_signed_in? %>
          <div class="user_nav grid-6">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete },class: :nav__logout %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div>
            <% else %>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
       <div class="greeting"> 
        <%# <% こんにちは、とりやまあきらさん %> 
         <%= link_to "ユーザー名さん", root_path, class: :greeting__link%>
       </div> 
    <%# <% // ログインしているときは上記を表示する %> 
    <div class="card__wrapper">
      <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
      <%= form_with model: @prototype, url: prototypes_path, local: true, multipart: true do |f| %>
        <div class="field">
          <%= f.label :title, "プロトタイプの名称" %><br />
          <%= f.text_field :title, id: "prototype_title", autofocus: true %>
        </div>
        <div class="field">
          <%= f.label :catch_copy, "キャッチコピー" %><br />
          <%= f.text_area :catch_copy, id: "prototype_catch_copy" %>
        </div>
        <div class="field">
          <%= f.label :concept, "コンセプト" %><br />
          <%= f.text_area :concept, id: "prototype_concept" %>
        </div>
        <div class="field">
          <%= f.label :image, "プロトタイプの画像" %><br />
          <%= f.file_field :image, id: "prototype_image" %>
        </div>
        <div class="actions">
          <%= f.submit "投稿する" %>
        </div>
      <% end %>
    </div>
  </div>
</div>